version: "3.7"

# Shared environment variables
x-default-env: &defaultEnv
  MINIO_HOST: minio
  MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
  MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  MONGO_URL: ${MONGO_URL}
  TEMPORAL_ADDRESS: ${TEMPORAL_ADDRESS}
  TEMPORAL_NAMESPACE: ${TEMPORAL_NAMESPACE}

services:
  app:
    extends:
      file: docker-compose.base.yaml
      service: app
    environment:
      <<: *defaultEnv
      NEXT_PUBLIC_API_URL: ${PUBLIC_API_URL}
  worker-1:
    extends:
      file: docker-compose.base.yaml
      service: worker
  worker-2:
    extends:
      file: docker-compose.base.yaml
      service: worker
  worker-3:
    extends:
      file: docker-compose.base.yaml
      service: worker
    environment:
      <<: *defaultEnv
      PUBLIC_API_URL: ${PUBLIC_API_URL}
  # STORAGE
  minio:
    extends:
      file: docker-compose.base.yaml
      service: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - miniostorage:/data
  temporal-postgresql:
    extends:
      file: docker-compose.base.yaml
      service: temporal-postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - temporal-network
    volumes:
      - temporal-postgresql:/var/lib/postgresql/data
  mongodb:
    extends:
      file: docker-compose.base.yaml
      service: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
  # TEMPORAL
  temporal:
    extends:
      file: docker-compose.base.yaml
      service: temporal
    networks:
      - temporal-network
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=temporal-postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
  temporal-ui:
    extends:
      file: docker-compose.base.yaml
      service: temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    networks:
      - temporal-network
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
  ferretdb-network:
    driver: bridge
    name: ferretdb-network
volumes:
  miniostorage:
  temporal-postgresql:
  mongodb:
