version: "3.7"

services:
  # STORAGE
  temporal-postgresql:
    extends:
      file: docker-compose.base.yaml
      service: temporal-postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - temporal-network
    volumes:
      - temporal-postgresql:/var/lib/postgresql/data
  mongodb:
    extends:
      file: docker-compose.base.yaml
      service: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
  # TEMPORAL
  temporal:
    extends:
      file: docker-compose.base.yaml
      service: temporal
    networks:
      - temporal-network
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=temporal-postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
  temporal-ui:
    extends:
      file: docker-compose.base.yaml
      service: temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    networks:
      - temporal-network
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
  ferretdb-network:
    driver: bridge
    name: ferretdb-network
volumes:
  temporal-postgresql:
  mongodb:
