version: "3.7"

services:
  app:
    extends:
      file: docker-compose.yml
      service: app
  worker-1:
    extends:
      file: docker-compose.yml
      service: worker
  worker-2:
    extends:
      file: docker-compose.yml
      service: worker
  worker-3:
    extends:
      file: docker-compose.yml
      service: worker
  # STORAGE
  minio:
    extends:
      file: docker-compose.yml
      service: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - miniostorage:/data
  temporal-postgresql:
    extends:
      file: docker-compose.yml
      service: temporal-postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - temporal-network
    volumes:
      - postgresql:/var/lib/postgresql/data
  mongodb:
    extends:
      file: docker-compose.yml
      service: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
  # TEMPORAL
  temporal:
    extends:
      file: docker-compose.yml
      service: temporal
    networks:
      - temporal-network
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
  temporal-ui:
    extends:
      file: docker-compose.yml
      service: temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    networks:
      - temporal-network
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
  ferretdb-network:
    driver: bridge
    name: ferretdb-network
volumes:
  miniostorage:
  temporal-postgresql:
  mongodb:
